---
driver_plugin: joyent
driver_config:
  joyent_username: <%= ENV['MANTA_USER'] %>
  joyent_keyfile: "<%= ENV['HOME'] %>/.ssh/id_rsa"
  joyent_keyname: <%= ENV['MANTA_KEY_ID'] %>
  joyent_url: <%= ENV['JOYENT_API_URL'] %>
  joyent_version: '~7.0'
  joyent_flavor_id: g3-highcpu-1.75-kvm

platforms:
- name: smartos-base64_14.3.0
  provisioner:
    name: chef_zero
    sudo: true
    require_chef_omnibus: '11.16.4'
    chef_omnibus_url: https://raw.github.com/wanelo-chef/chef-bootstrap/master/latest.sh
  driver_config:
    joyent_image_id: 62f148f8-6e84-11e4-82c5-efca60348b9f
    username: root
- name: ubuntu-certified-14.04_20150225.2
  provisioner:
    name: chef_zero
    sudo: true
    require_chef_omnibus: '11.16.4'
  driver_config:
    joyent_image_id: c864f104-624c-43d2-835e-b49a39709b6b
    username: ubuntu

suites:
  - name: nad-o-matic
    run_list:
      - recipe[nad-o-matic]

