name             'nad-o-matic'
maintainer       'Blake Irvin'
maintainer_email 'blake.irvin@yetu.com'
license          'MIT'
description      'Installs/Configures nad-o-matic'
long_description 'Installs/Configures nad-o-matic'
version          '0.5.1'

depends 'nad'
depends 'smf'
